name: snapkit
description: A Flutter Plugin for integrating with Snapchat's SnapKit on iOS & Android
version: 0.0.2
homepage: https://github.com/TimmyRB/Flutter-SnapKit

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jacobbrasil.snapkit
        pluginClass: SnapKitPlugin
      ios:
        pluginClass: SnapKitPlugin