name: snapkit
description: A Flutter Plugin for integrating with Snapchat's SnapKit on iOS & Android
version: 0.0.1
authors: 
  - ottomated <otto@ottomated.net>
  - jacobbrasil <https://jacobbrasil.com>
homepage: https://github.com/TimmyRB/Flutter-SnapKit

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.jacobbrasil.snapkit
    pluginClass: SnapKitPlugin