name: snapchat_androidx
description: A fork of ottomated's Snapchat library for interfacing with the Snapchat developer kit 
version: 0.1.0
authors: 
 - ottomated <otto@ottomated.net>
 - ewpratten <ewpratten@gmail.com>
homepage: https://github.com/Ewpratten/flutter_snapchat_androidX

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: net.ottomated.snapchat
    pluginClass: SnapchatPlugin
